spring.application.name=smm-backend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.security.user.name=
spring.security.user.password=

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.csrf.enabled=false
springdoc.packagesToScan=rs.ac.metropolitan.socialmediamanager

jwt.secret=veryVerySecretKeyThatIsAtLeast32CharactersLong
jwt.expiration=86400000

instagram.access.token =IGAAUhYxZCg4g5BZAGJtV0d3X0prdERyUFU1NGNDMjB4WlNjNWxTZAGRBM0VEQnhIWDJWczBVWUM2OFZAaczhsRHBnRUs2SUlMcDN2aEtHZAWpua1lKSTFIQ1pIa2haelBhXzN1RklSNFZA4ZAEEtZAE5BYWRFblVleXVvSXBQWnJPNkh3YwZDZD
instagram.api.url =https://graph.instagram.com

app.base-url=http://127.0.0.1:8080

spotify.client.id=17d558d4abfa4c1fb44888ef1dd12546
spotify.client.secret=cd641f8a6cab4ff587c15773cfb214f9
spotify.redirect.uri=http://127.0.0.1:8080/api/spotify/callback